version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=temporal

  temporal:
    image: temporalio/auto-setup:1.18.0
    depends_on:
      - mysql
    environment:
      - DB=mysql
      - DB_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PWD=root
      - MYSQL_SEEDS=temporal
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    ports:
      - 7233:7233
    volumes:
      - ./development-sql.yaml:/etc/temporal/config/development-sql.yaml

  temporal-admin-tools:
    container_name: temporal-admin-tools
    image: temporalio/admin-tools:1.18.0
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233